name: Feature Request
description: Request a Feature
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new Feature or an update to an existing Feature in the Draw Steel system for FoundryVTT
  - type: textarea
    id: user-experience
    attributes:
      label: User Experience
      description: What problem does this solve? What should it function like?
      placeholder: As a [Module Developer/Game Master/Player] I would like [Functionality] so I can [Underlying purpose]
    validations:
      required: true
